#library "ZDGHOST"
#include "zcommon.acs"
#include "GetSrcPort.acs" // must put code from SRCPORT into file "GetSrcPort.acs" next to "zcommon.acs" when compiling

#define TID_CRUSHER_VISITOR 10666
#define TID_GHOST_MONSTER 10667
#define TID_TEMP 6666

// Hardcoded coordinates for Spawning SecActEnter things
// inside crusher sectors. (X, Y)
int SecActCoordinates[6][2] = {
	{ -1080.0, -1640.0 },
	{  -952.0, -1640.0 },
	{  -824.0, -1640.0 },
	{  -696.0, -1640.0 },
	{  -568.0, -1640.0 },
	{  -440.0, -1640.0 } 
};

Script "ZDOOMMAP30PATCH" OPEN
{
	if (GetCVar("zdghost_map30patch_disable") > 0) 
		Terminate;
		
	if ((GetSrcPort() == PORT_ZDOOM) || (GetSrcPort() == PORT_GZDOOM) || (GetSrcPort() == PORT_LZDOOM) || (GetSrcPort() == PORT_ZANDRONUM) || (GetSrcPort() == PORT_ZDAEMON))
{		
	int i, x, y;
	
	int levnum = GetLevelInfo (LEVELINFO_LEVELNUM);
	if (levnum == 30)
	{
		// Make crushers next to viles useless
		for (i = 103; i <= 108; i++)
			Ceiling_CrushAndRaiseDist(i, 204, 2, 0);
			
		// Spawn sector action things in crusher sectors
		for (i = 0; i < 6; i++)
		{
			x = SecActCoordinates[i][0];
			y = SecActCoordinates[i][1];
			
			SpawnForced("SecActEnter", x, y, 0, TID_TEMP, 0);
			SetThingSpecial(TID_TEMP, ACS_ExecuteAlways, 255);
			SetActorProperty(TID_TEMP, APROP_Ambush, TRUE); // Monsters activate
			
			// After we are done adjusting the thing, remove the 
			// temporary thing tag from it.
			Thing_ChangeTID(TID_TEMP, 0);
		}
	}
	}
}

function bool NoActivator(void)
{
	if (ClassifyActor(0) == ACTOR_NONE) return TRUE;
	if (ClassifyActor(0) & ACTOR_WORLD) return TRUE;
	return FALSE;
}

function bool InsideCrusherSector(void)
{
	if (NoActivator()) return FALSE;
	
	int x = GetActorX(0);
	int y = GetActorY(0);

	// Hardcoded coordinates
	// Just using a wide rectangle that spans all the crushers here.
	// This could be made more accurate by specifying coordinates for each
	// crusher sector separately.
	if ( (x > -1088.0) && (x <  -320.0) &&
		 (y < -1520.0) && (y > -1648.0) )
	{
		return TRUE;
	}
	return FALSE;
}

#define MI_DEC_NORMAL 0
#define MI_DEH_NORMAL 1
#define MI_DEC_GHOST 2
#define MI_DEH_GHOST 3
#define NUM_MI 4
#define NUM_MI_TYPES 11
int MonsterInfo[NUM_MI_TYPES][NUM_MI] = {
	{"DoomImp"       , "DoomImp"    , "GhostDoomImp"    , "PointPusher" },
	{"Demon"         , "Demon"      , "GhostDemon"      , "PointPuller" },
	{"Spectre"       , "Spectre"    , "GhostSpectre"    , "MBFHelperDog"},
	{"NewCacodemon"  , "Cacodemon"  , "GhostCacodemon"  , "PlasmaBall1" },
	{"NewBaronOfHell", "BaronOfHell", "GhostBaronOfHell", "PlasmaBall2" },
	{"NewHellKnight" , "HellKnight" , "GhostHellKnight" , "EvilSceptre" },
	{"Revenant"      , "Revenant"   , "GhostRevenant"   , "UnholyBible" },
	{"Arachnotron"   , "Arachnotron",   "", "" },
	{"Archvile"      , "Archvile"   ,   "", "" },
	{"Fatso"         , "Fatso"      ,   "", "" },
	{"NoRaiseElemental" , "PainElemental", "", "" }
};

// Originally had these integer values in the previous array, but got weird
// values after compiling. Separating them from the strings fixed the issue.
#define MI2_DMG_CYCLE 0
#define MI2_DMG_AMOUNT 1
#define MI2_GHOST 2
#define MI2_RESURRECT 3
#define NUM_MI2 4
int MonsterInfo2[NUM_MI_TYPES][NUM_MI2] = {
 { 199, 60, TRUE, TRUE }, // DoomImp
 { 199, 60, TRUE, TRUE }, // Demon
 { 199, 60, TRUE, TRUE }, // Spectre
 { 199, 78, TRUE, TRUE }, // Cacodemon
 { 199, 70, TRUE, TRUE }, // BaronOfHell
 { 199, 70, TRUE, TRUE }, // HellKnight
 { 199, 60, TRUE, TRUE }, // Revenant
 { 199, 70, FALSE, TRUE  }, // Arachnotron
 { 199, 60, FALSE, FALSE }, // Archvile
 { 199, 70, FALSE, TRUE  }, // Fatso
 { 199, 78, FALSE, FALSE }  // PainElemental
};

function int GetMonsterInfoIndex(void)
{
	int i;	
	str class = GetActorClass(0);
	//Log(s:"class is '",s:class,s:"'.");

	// Comparing priority when it comes to dehacked/decorate class names.
	int a, b;
	if (GetSrcPort() == PORT_ZDAEMON) { a = MI_DEH_NORMAL; b = MI_DEC_NORMAL; }
	else                     { a = MI_DEC_NORMAL; b = MI_DEH_NORMAL; }

	// Might as well check both decorate and dehacked names here
	for (i = 0; i < NUM_MI_TYPES; i++)
	{
		// StrCmp/StrICmp is needed here, at least for ZDaemon.
		if (StrICmp(class, MonsterInfo[i][a]) == 0) return i;
	}
	for (i = 0; i < NUM_MI_TYPES; i++)
	{
		if (StrICmp(class, MonsterInfo[i][b]) == 0) return i;
	}
	return -1;
}

// This script should be executed by monsters that enter the crusher sector.
Script 255 (void)
{
	// Ignore if not a monster
	if (!(ClassifyActor(0) & ACTOR_MONSTER)) Terminate;

	// Ignore ghost monsters
	if (ActivatorTID() == TID_GHOST_MONSTER) Terminate;

	// Prevent one monster from executing the script multiple times.
	if (ActivatorTID() == 0) Thing_ChangeTID(0, TID_CRUSHER_VISITOR);
	else Terminate;
	
	int dmg_cycle;
	int dmg_amount;
	int can_ghost;
	int can_res;
	
	// Figure out the monster type
	int mi_index = GetMonsterInfoIndex();
	if (mi_index == -1)
	{
		// If we get here, the monster is not one of the expected types.
		// Just use the DoomImp damage values for it.
		dmg_cycle = MonsterInfo2[0][MI2_DMG_CYCLE];
		dmg_amount = MonsterInfo2[0][MI2_DMG_AMOUNT];
		can_ghost = FALSE;
		can_res = FALSE;
	}
	else // Else use values according to type.
	{
		dmg_cycle = MonsterInfo2[mi_index][MI2_DMG_CYCLE];
		dmg_amount = MonsterInfo2[mi_index][MI2_DMG_AMOUNT];
		can_ghost = MonsterInfo2[mi_index][MI2_GHOST];
		can_res = MonsterInfo2[mi_index][MI2_RESURRECT];
	}

	//Log(s:"mi_index: ",d:mi_index,s:", dmg_cycle: ",d:dmg_cycle,s:", dmg_amount: ",d:dmg_amount);

	while (NoActivator() == FALSE)
	{
		while (GetActorProperty(0, APROP_Health) > 0)
		{
			// If within the crusher area
			if (InsideCrusherSector())
			{
				// Deal "crusher" damage between damage cycle tics
				if (Timer() % dmg_cycle == 0)
					Thing_Damage(0, dmg_amount, MOD_CRUSH);
			}
			Delay(1);
		}

		// If we get this far, the monster has died.
		while (GetActorProperty(0, APROP_Health) <= 0)
		{
			// If monster has disappeared or cannot be resurrected.
			if (NoActivator() || (can_res == FALSE))
			{
				Terminate; // Stop the script.
			}
			Delay(1); // Wait for Vile to resurrect
		}

		int x, y, z, angle, class;

		// If we get this far, the monster has been resurrected.
		if (InsideCrusherSector() && (can_ghost == TRUE)) // Check just in case
		{
			x = GetActorX(0);
			y = GetActorY(0);
			z = GetActorZ(0);
			angle = GetActorAngle(0);

			Thing_Remove(0); // Remove self

			// Spawn Ghost version according to thing type
			if (GetSrcPort() == PORT_ZDAEMON)
				class = MonsterInfo[mi_index][MI_DEH_GHOST]; // Dehacked
			else
				class = MonsterInfo[mi_index][MI_DEC_GHOST]; // Decorate
						
			SpawnForced(class, x, y, z, TID_GHOST_MONSTER, angle >> 8);
		}
		
		Delay(1);
	}
}
